/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.JobsController;
import icontrollers.IJobsController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Job;
import tools.DBConnection;

/**
 *
 * @author erik
 */
public final class JobView extends javax.swing.JFrame {

    DBConnection connection = new DBConnection();
    IJobsController ijc = new JobsController(connection.getConnection());
    /**
     * Creates new form RegionView
     */
    public JobView() {
        initComponents();
        ShowtableJobs();
    }

    public void resetTextJobs() {
        txt_jobId.setText("");
        txt_Job_Name.setText("");
        txt_Min_Salary.setText("");
        txt_Max_Salary.setEditable(true);
        btn_insertJob.setEnabled(true);
    }
    
    public void ShowtableJobs() {
        DefaultTableModel model =(DefaultTableModel) tbl_Job.getModel();
        Object[] row = new Object[4];
        List<Job> Jobs = new ArrayList<>();
        Jobs = ijc.getAll();
        for (int i = 0; i < Jobs.size(); i++) {
            row[0] = Jobs.get(i).getId();
            row[1] = Jobs.get(i).getTitle();
            row[2] = Jobs.get(i).getMin_Salary();
            row[3] = Jobs.get(i).getMax_Salary();
            model.addRow(row);       
        }
    }
    
    public void ShowtableJobs(String s) {
        DefaultTableModel model =(DefaultTableModel) tbl_Job.getModel();
        Object[] row = new Object[4];
        List<Job> Jobs = new ArrayList<>();
        Jobs = ijc.search(s);
        for (int i = 0; i < Jobs.size(); i++) {
            row[0] = Jobs.get(i).getId();
            row[1] = Jobs.get(i).getTitle();
            row[2] = Jobs.get(i).getMin_Salary();
            row[3] = Jobs.get(i).getMax_Salary();
            model.addRow(row);       
        }
    }
    
    public void updateTableJobs() {
        DefaultTableModel model = (DefaultTableModel) tbl_Job.getModel();
        model.setRowCount(0);
        ShowtableJobs();
    }
    
    public void updateTableJobs(String s) {
        DefaultTableModel model = (DefaultTableModel) tbl_Job.getModel();
        model.setRowCount(0);
        if (s == "") {
            ShowtableJobs();
        }
        ShowtableJobs(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_jobId = new javax.swing.JTextField();
        txt_Job_Name = new javax.swing.JTextField();
        btn_insertJob = new javax.swing.JButton();
        btn_updateJob = new javax.swing.JButton();
        btn_deleteJob = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Job = new javax.swing.JTable();
        txt_Min_Salary = new javax.swing.JTextField();
        txt_Max_Salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("New Jobs");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("name");

        txt_jobId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_jobId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobIdActionPerformed(evt);
            }
        });

        txt_Job_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Job_NameActionPerformed(evt);
            }
        });

        btn_insertJob.setText("Insert");
        btn_insertJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertJobActionPerformed(evt);
            }
        });

        btn_updateJob.setText("Update");
        btn_updateJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateJobActionPerformed(evt);
            }
        });

        btn_deleteJob.setText("Delete");
        btn_deleteJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteJobActionPerformed(evt);
            }
        });

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        tbl_Job.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job_Id", "Job_Name", "Min_Salary", "Max_Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Job.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_JobMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Job);

        txt_Min_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Min_SalaryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Min Salary");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Max Salary");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_jobId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Max_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Min_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_insertJob)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_updateJob)
                                        .addComponent(txt_Job_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(148, 148, 148)
                                    .addComponent(btn_deleteJob))
                                .addComponent(jButton4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Min_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Job_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Max_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertJob)
                    .addComponent(btn_updateJob)
                    .addComponent(btn_deleteJob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jobIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jobIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jobIdActionPerformed

    private void txt_Min_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Min_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Min_SalaryActionPerformed

    private void btn_updateJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateJobActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "apakah anda yakin melakukan insert? ", "confirm insert ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,ijc.update(txt_jobId.getText(), txt_Job_Name.getText(), txt_Min_Salary.getText(), txt_Max_Salary.getText()));
            updateTableJobs();
            resetTextJobs();
        }
      
    }//GEN-LAST:event_btn_updateJobActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_Job_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Job_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Job_NameActionPerformed

    private void btn_insertJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertJobActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "apakah anda yakin melakukan update? ", "confirm update ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,ijc.insert(txt_jobId.getText(), txt_Job_Name.getText(), txt_Min_Salary.getText(), txt_Max_Salary.getText()));
              updateTableJobs();
            resetTextJobs();
        }
    }//GEN-LAST:event_btn_insertJobActionPerformed

    private void tbl_JobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_JobMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_Job.getModel();
        int SelectedRowIndex = tbl_Job.getSelectedRow();

        txt_jobId.setEditable(false);
        btn_insertJob.setEnabled(false);
        txt_jobId.setText(model.getValueAt(SelectedRowIndex, 0).toString());
        txt_Job_Name.setText(model.getValueAt(SelectedRowIndex,1).toString());
        txt_Min_Salary.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        txt_Max_Salary.setText(model.getValueAt(SelectedRowIndex, 3).toString());
        
    }//GEN-LAST:event_tbl_JobMouseClicked

    private void btn_deleteJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteJobActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "apakah anda yakin melakukan delete? ", "confirm delete ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,ijc.delete(txt_jobId.getText()));
            updateTableJobs();
            resetTextJobs();
        }
    }//GEN-LAST:event_btn_deleteJobActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
         updateTableJobs(txt_search.getText());
    }//GEN-LAST:event_txt_searchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteJob;
    private javax.swing.JButton btn_insertJob;
    private javax.swing.JButton btn_updateJob;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Job;
    private javax.swing.JTextField txt_Job_Name;
    private javax.swing.JTextField txt_Max_Salary;
    private javax.swing.JTextField txt_Min_Salary;
    private javax.swing.JTextField txt_jobId;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
